name: Generate ASCII Artwork

on:
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    #   - name: Checkout Repo
    #     uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: Sleep for 30 seconds
        run: sleep 30

    #   - name: Upload dragon.txt
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: dragon-file
    #       path: dragon.txt

  test_job_2:
    runs-on: ubuntu-latest
    # needs: build_job_1
    steps:
    #   - name: Download dragon.txt
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: dragon-file

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    # needs: test_job_2
    steps:
    #   - name: Download dragon.txt
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: dragon-file

      - name: Read File
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying..."
